config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    resources :tasks
  end
  

  devise_for :users
  get "pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks

    validates :category_name , presence: true, length: {minimum: 5}
    validates :description , presence: true

end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
    belongs_to :user

    validates :task_name , presence: true
    validates :desc , presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :categories
  has_many :tasks, through: :categories
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  add_flash_types :info, :error, :warning, :danger,:success
  before_action :authenticate_user!
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit,:update,:destroy]

  def index; end

  def show; end

  def new
     @category = current_user.categories.new
  end

  def edit; end

  def create
    # @cat_list = current_user.categories
    @category= current_user.categories.new(category_params)
     if @category.save
      flash[:success] = "Category successfully Save!"
      redirect_to root_path
    else
      flash[:danger] = "Please check your details!"
      render "pages/home", status: :unprocessable_entity
    end
  end

  def update
     if @category.update(category_params)
      # binding.b
      flash[:success] = "Category successfully updated!"
      redirect_to root_path
    else
      # binding.b
      flash[:danger] = "Please check your details!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @category.destroy
    @category.update(is_deleted: true)
     flash[:success] = "Deleted successfully"
    redirect_to root_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:category_name, :description)
  end

   def set_category
       @category = current_user.categories.find(params[:id])
   end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def home
    @filter = "All";
    @today = Date.today.strftime("%F")
      if params[:filter] && params[:filter] !="All"
        @filter = "Today"
      end
    @cat_list = current_user.categories.where(is_deleted: false).order(:category_name)
    @category = current_user.categories.new
    # @tasks = current_user.tasks.where(due_date: Date.today.strftime("%F"))

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
add_flash_types :info, :error, :warning
before_action :set_category, only: [:edit,:update,:destroy,:create,:index,:show]
rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
def index
        # @category = current_user.categories.find(params[:category_id])
        if params[:filter] && params[:filter] !="All"
            today = Date.today.strftime("%F")
            @tasks = @category.tasks.where(due_date: today)
        else
            @tasks = @category.tasks
        end
        # @tasks = @category.tasks
        @task = @category.tasks.new
    end

    def show
         @task = @category.tasks.find(params[:id])
    end

    def new ;end

    def edit 
        # @category = current_user.categories.find(params[:category_id])
        @tasks = @category.tasks
        @task = @category.tasks.find(params[:id])
    end

    def update 
        #  @tasks = @category.tasks
         @task = @category.tasks.find(params[:id])
         @task.user_id = current_user.id
        # binding.b
         if @task.update(task_params)
            flash[:info] = " Task successfuly updated"
            redirect_to category_tasks_path(@category)
         else
            flash[:info] = " Please check ur details"
            render :edit, status: :unprocessable_entity
         end
    end

    def create 
         @tasks = @category.tasks
         @task = @category.tasks.build(task_params)
         @task.user_id = current_user.id
        # binding.b
         if @task.save
            flash[:success] = " Task successfuly created"
            redirect_to category_tasks_path(@category)
         else
            flash[:danger] = " Please check ur details"
            render :index, status: :unprocessable_entity
         end
    end

    def destroy 
        @task = @category.tasks.find(params[:id])
        @task.destroy
        flash[:success] = "Deleted successfully"
        # redirect_to article_path(@article), status: :see_other
        redirect_to category_tasks_path(@category), status: :see_other
    end

    private
    def task_params
        params.require(:task).permit(:task_name,:desc,:due_date)
    end
     def set_category
        @category = current_user.categories.find(params[:category_id])
    end

    def record_not_found
        # @category = current_user.categories.find(params[:category_id])
        flash[:danger] = "No record found"
        redirect_to root_path, status: :see_other
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb


<div class="rounded m-2 p-2 ">
    <%= form_with model: category do |form| %>
        <div class="mb-3">
            <%= form.label :category_name, class: "form-label" %><br />
            <%= form.text_field :category_name , class: "form-control border   border-secondary " %>
                <% category.errors.full_messages_for(:category_name).each do |message| %>
                    <div class="text-danger">
                        <%= message %>
                    </div>
                <% end %>
        </div>

        <div class="mb-3">
            <%= form.label :description , class: "form-label" %><br />
            <%= form.text_area :description,class: "form-control border border-secondary " %>
                <% category.errors.full_messages_for(:description).each do |message| %>
                    <div class="text-danger">
                        <%= message %>
                    </div>
                <% end %>
        </div>
        <%= form.submit "Submit" , class: "btn btn-dark btn-sm" %>
    <% end %>
</div>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb

<%= link_to "Back" ,root_path, class: "btn btn-outline-dark w-25" %>
    <br>
<h1>Edit</h1>
<div class="rounded m-2 p-2 ">
    <%= form_with model: @category, local: true do |form| %>
        <div class="mb-3">
            <%= form.label :category_name, class: "form-label" %><br />
            <%= form.text_field :category_name , class: "form-control border
                    border-secondary " %>

            <% @category.errors.full_messages_for(:category_name).each do |message| %>
                <div class="text-danger">
                    <%= message %>
                </div>
            <% end %>
        </div>

        <div class="mb-3">
            <%= form.label :description , class: "form-label" %><br />
            <%= form.text_area :description,class: "form-control border border-secondary " %>

            <% @category.errors.full_messages_for(:description).each do |message| %>
                <div class="text-danger">
                    <%= message %>
                </div>
            <% end %>
        </div>
        <%= form.submit "Submit" , class: "btn btn-dark" %>
    <% end %>
</div>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

<div class="rounded m-2 p-2 w-50">
    <%= form_with model: @category do |form| %>
        <div class="mb-3">
            <%= form.label :category_name, class: "form-label" %><br />
                <%= form.text_field :category_name , class: "form-control border
    border-secondary w-50" %>

                    <% @category.errors.full_messages_for(:category_name).each do |message| %>
                        <div class="text-danger">
                            <%= message %>
                        </div>
                        <% end %>
        </div>

        <div class="mb-3">
            <%= form.label :description , class: "form-label" %><br />
                <%= form.text_area :description,class: "form-control border border-secondary w-50" %>

                    <% @category.errors.full_messages_for(:description).each do |message| %>
                        <div class="text-danger">
                            <%= message %>
                        </div>
                        <% end %>
        </div>

        <%= form.submit "Submit" , class: "btn btn-primary btn-sm" %>
            <% end %>
</div>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

<h5>Add a comment:</h5>
<%= render @category.tasks %>

<br>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "JournalApp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <!-- <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png"> -->
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

      <%# fontawesome %>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
          integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
        <%# bootstrap %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  </head>

  <body>

    <nav class="navbar bg-light-subtle text-info-emphasis">
      <div class="container d-flex justify-content-between">
        <a class="navbar-brand" href="#">
          <!-- <img src="/app/assets/images/favicon.png" alt="" width="30" height="24"> -->
           <h4><%= image_tag 'favicon.png' , style: 'height:50px;width:auto;', class: "mx-2" %>Journal App</h4>
        </a>
          <% if user_signed_in? %>
            <%= link_to "Logout" ,destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
            class: "btn btn-outline-dark" %>
          <% end %>
      </div>
    </nav>

    <div class="text-center container my-2">
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %>">
          <%= msg %>
        </div>
      <% end %>
    </div>

    <div class="container-fluid my-2 text-center d-flex flex-column justify-content-center w-50">
      <%= yield %>
    </div>
    

  </body>
</html>

app/views/pages/home.html.erb
<br>


   
<div class="d-flex justify-content-between">
    <div >
        <h4 class="text-start">CATEGORIES</h4>
    </div>
    <div >
        <div class="d-flex flex-row">
            <div class="mx-2">
                <%= form_with model: [@cat_list ], url: root_path, method: :get do |form| %>
                    <%= select_tag(:filter, options_for_select([["All"],["Today"]], params[:filter] ), class:"select form-control
                        btn btn-outline-dark" , onchange: "this.form.submit();" ) %>
                        <% end %>
            </div>
            <div>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-outline-dark" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Add Category
                </button>
            </div>
        </div>
        
        
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">New Category</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <%= render "categories/form" , category: @category %>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
<hr>


<% @cat_list.each do |cat| %>
    <% if cat.persisted? %>
        <div class="card mt-2 border border-secondary w-75" >
            <div class="card-header">
                <div class="d-flex flex-row justify-content-between">
                    <div>
                        <strong class="text-uppercase"><%= cat.category_name %></strong>
                    </div>
                    <div>
                        <%= link_to icon('fa-solid', 'pen-to-square' ), edit_category_path(cat), class: "btn btn-sm" %>
                        <%= link_to icon('fa-solid', 'trash' ), category_path(cat), data: { turbo_method: :delete,
                            turbo_confirm: "Are you sure?" } , class: "text-danger btn btn-sm" %>
                        <%= link_to icon('fa-solid', 'eye' ), category_tasks_path(cat) , class: "btn btn-sm" %>
                    </div>
                 
                </div>
            </div>
           
                <% @cat=Category.find(cat.id) %>
                <% if @filter && @filter=="Today" %>
                    <% @cat_tasks=@cat.tasks.where(due_date:  @today).order(created_at: :desc) %>
                <% else %>
                    <% @cat_tasks=@cat.tasks.order(created_at: :desc) %>
                <% end %>

                    <% if @cat_tasks.any? %>
                        <ol class="list-group list-group-numbered list-group-flush text-start">
                            <% @cat_tasks.each do |task| %>
                                <% if task.persisted? %>
                                    <li class="list-group-item ">
                                        <strong class="mr-2 text-capitalize">
                                            <%= task.task_name %>
                                        </strong>
                                        <small class="fst-italic">
                                            (Due Date : <%= task.due_date.strftime("%b %d, %Y") %>)
                                        </small>
                                    </li>
                                <% end %>
                            <% end %>
                        </ul>
                    <% else %>
                        <p>No tasks found.</p>
                    <% end %>

            <!-- </ul> -->
        </div>
               
           
           
                   
         
    <% end %>
<% end %>

app/views/tasks/_form.html.erb
<div class="rounded m-2 p-2 ">
    <%= form_with model: [category,task ] do |form| %>
        <div class="mb-3">
            <%= form.label :task_name, class: "form-label" %><br />
            <%= form.text_field :task_name , class: "form-control border border-secondary " %>
                <% task.errors.full_messages_for(:task_name).each do |message| %>
                    <div class="text-danger">
                        <%= message %>
                    </div>
                <% end %>
        </div>

        <div class="mb-3">
            <%= form.label :desc , class: "form-label" %><br />
                <%= form.text_area :desc,class: "form-control border border-secondary " %>
                <% task.errors.full_messages_for(:desc).each do |message| %>
                    <div class="text-danger">
                        <%= message %>
                    </div>
                <% end %>
        </div>

        <div class="mb-3">
            <%= form.label :due_date , class: "form-label" %><br />
                <%= form.date_select :due_date,class: "form-control border border-secondary " %>
                <% task.errors.full_messages_for(:due_date).each do |message| %>
                    <div class="text-danger">
                        <%= message %>
                    </div>
                <% end %>
        </div>
        <%= form.submit "Submit" , class: "btn btn-dark btn-sm" %>
    <% end %>
</div>

app/views/tasks/_task.html.erb
<% tasks.each do |task| %>
    <% if task.persisted? %>
        <tr>
            <td>
                <%= task.task_name %> 
            </td>
            <td>
                <%= task.due_date.strftime("%b %d, %Y") %>
            </td>
            <td>
                <%= link_to icon('fa-solid', 'pen-to-square') , edit_category_task_path(task.category_id,task), class: "btn btn-sm" %>
            </td>
            <td>
                <%= link_to icon('fa-solid', 'trash') , category_task_path(task.category_id, task), data: { turbo_method: :delete,
                        turbo_confirm: "Are you sure?" }, class: "btn btn-sm text-danger" %>
            </td>
            <td>
                <%= link_to icon('fa-solid', 'eye') , category_task_path(task.category_id, task), class: "btn btn-sm" %>
            </td>
        </tr>
    <% end %>
<% end %>

app/views/tasks/edit.html.erb

<%= link_to "back",category_tasks_path(@category), class: "btn btn-outline-dark w-25" %>
<h1>Edit</h1>
<%= render "form" , task: @task , category: @category%>

app/views/tasks/index.html.erb
<%= link_to "Back",root_path, class: "btn btn-outline-dark w-25" %>
<br>
<h2>Category : <%= @category.category_name %> </h2>
<h5 class="fst-italic">( <%= @category.description %> )</h5>

<br>
<div class="d-flex flex-row-reverse">
    <div>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-outline-dark mx-2" data-bs-toggle="modal" data-bs-target="#taskModal">
            Add Task
        </button>
    </div>
    
    <div>
        <%= form_with model: [@category,@task ], url: category_tasks_path(@category), method: :get do |form| %>
            <%= select_tag(:filter, options_for_select([["All"],["Today"]], params[:filter] ), class:"select form-control btn btn-outline-dark" ,
                onchange: "this.form.submit();" ) %>
        <% end %>
    </div>
    

   
</div>

    <!-- Modal -->
    <div class="modal fade" id="taskModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">New Task</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <%= render "form" , task: @task , category: @category%>
                </div>
            </div>
        </div>
    </div>



<hr>




<table class="table">
    <thead>
        <tr>
            <th>TASKS</th>
            <th>DUE DATE</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <%= render "task" , tasks: @tasks %>
    </tbody>
</table>




app/views/tasks/show.html.erb

<%= link_to "back" ,category_tasks_path(@category), class: "btn btn-outline-dark w-25" %>
<h1> <%= @task.task_name %></h1>
<h6 class="fst-italic">( <%= @task.desc %> )</h6>